Controllers/tb_buyController.cs
using Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Store.Controllers
{
    public class tb_buyController : Controller
    {
        private PetStoreEntities4 db=new PetStoreEntities4();
        // GET: tb_buy
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrdersList() 
        {
            return View(db.tb_buy.ToList());
        }
    }
}

Views/Shared/UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("PET SHOP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = " " }, new { @class = "nav-link" })</li>
                    @if (Session["isLoggedIn"] != null && (bool)Session["IsLoggedIn"])
                    {
                        <span class="navbar-text ml-auto">Welcome @Session["UserName"]</span>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger">
        <div class="container">
            @Html.ActionLink("PET SHOP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Login/Register", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)




    <style>
        /* Add a black background color to the top navigation */
        *{
            margin:0px;
            padding:0;
            font-family:'Dosis', sans-serif;
            font-size: 18px;
            
        }
        .navbar-nav li a{
            color:#ffffff;
            padding:0 10px;
            position: relative;
        }

        .navbar-nav li a:hover, .navbar-nav li.active a {
            content: '';
            background: #000000;
            transform: translateX();
            transition: 1.25s;
        }
        
        
    </style>



</body>



</style>
</html>

Views/Shared/_newLayout.cshtml
<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")

</head>

<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">

        <div class="container">

            @Html.ActionLink("PET CART", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>

            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" style="margin-left: 900px">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = " " }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Orders", "OrdersList", "tb_buy", new { area = " " }, new { @class = "nav-link" })</li>
                </ul>

                @if (Session["isLoggedIn"]!=null && (bool)Session["IsLoggedIn"])
                 {
                    <span class="navbar-text ml-auto">Welcome @Session["UserName"]</span>
                 }
            </div>

        </div>

    </nav>

    <div class="container body-content"></div>

        @RenderBody()

        <hr />

        <!--<footer>

                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>

            </footer>

        </div>-->

        @Scripts.Render("~/bundles/jquery")

        @Scripts.Render("~/bundles/bootstrap")

        @RenderSection("scripts", required: false)

</body>

</html>